
all: AlgThread.class AlgAnimApp.class TextFrame.class \
	GraphPanel.class AlgAnimFrame.class ComPanel.class \
	ControlPanel.class GraphMST.class Graph.class \
	LegendPanel.class GraphDij.class Arrow.class \
	ClassInterface.class CostMatrix.class Edge.java \
	ExtraFrame.class Forest.class Node.class \
	PriorityQueue.class Tree.class

ClassInterface.class: ClassInterface.java
	javac ClassInterface.java

Node.class: Node.java
	javac Node.java


Arrow.class: Arrow.java
	javac Arrow.java

Edge.class: Edge.java
	javac Edge.java

ControlPanel.class: ControlPanel.java
	javac ControlPanel.java

ComPanel.class: ComPanel.java
	javac ComPanel.java

LegendPanel.class: LegendPanel.java
	javac LegendPanel.java

CostMatrix.class: CostMatrix.java
	javac CostMatrix.java

PriorityQueue.class: PriorityQueue.java
	javac PriorityQueue.java

Tree.class: Tree.java
	javac Tree.java

Forest.class: Forest.java
	javac Forest.java

ExtraFrame.class: ExtraFrame.java
	javac ExtraFrame.java

Graph.class: Graph.java
	javac Graph.java

GraphPanel.class: GraphPanel.java
	javac GraphPanel.java

GraphMST.class: GraphMST.java
	javac GraphMST.java

GraphDij.class: GraphDij.java
	javac GraphDij.java

TextFrame.class: TextFrame.java
	javac TextFrame.java

AlgThread.class: AlgThread.java
	javac AlgThread.java

AlgAnimApp.class: AlgAnimApp.java
	javac AlgAnimApp.java

AlgAnimFrame.class: AlgAnimFrame.java
	javac AlgAnimFrame.java

run:
	appletviewer tqs.html

clean:
	\rm -f *.class
