
all: AlgThread.class AlgAnimApp.class TextFrame.class \
	DrawingPanel.class AlgAnimFrame.class ComPanel.class \
	ControlPanel.class Node.class TreeUtils.class

ControlPanel.class: ControlPanel.java
	javac ControlPanel.java

ComPanel.class: ComPanel.java
	javac ComPanel.java

DrawingPanel.class: DrawingPanel.java
	javac DrawingPanel.java

TextFrame.class: TextFrame.java
	javac TextFrame.java

AlgThread.class: AlgThread.java
	javac AlgThread.java

AlgAnimApp.class: AlgAnimApp.java
	javac AlgAnimApp.java

AlgAnimFrame.class: AlgAnimFrame.java
	javac AlgAnimFrame.java

Node.class: Node.java
	javac Node.java

TreeUtils.class: TreeUtils.java
	javac TreeUtils.java

run:
	appletviewer tts.html

clean:
	\rm -f *.class
